sudo: required
services:
  - docker
before_install:
  - docker image build -t sunnyjohal/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker container run sunnyjohal/react-test npm test -- --coverage
after_success:
  - docker image build -t sunnyjohal/multi-client ./client
  - docker image build -t sunnyjohal/multi-nginx ./nginx
  - docker image build -t sunnyjohal/multi-server ./server
  - docker image build -t sunnyjohal/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to docker hub
  - docker push sunnyjohal/multi-client
  - docker push sunnyjohal/multi-nginx
  - docker push sunnyjohal/multi-server
  - docker push sunnyjohal/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-026515532791
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
